.gitignore
src/Pages/Login/Login.jsx
src/Pages/Register/Register.jsx

- enable submit on enter
- basic keyboard accessibility
- remove warning and unused vars

login-register-form update

---

package-lock.json
package.json
src/App.js
src/Components/AsideLeft/AsideLeft.jsx
src/Components/SideNav/SideNav.jsx

- sidenav and modals were overlapping
- changed zIndex of sidenav to fix it

fixed sidenav and modal overlapping issue

---

src/Components/NavBar/NavBar.jsx

now profile pic can be seen on navbar

---

src/Components/JoinRequests/JoinRequests.jsx

Issue #34 and #40 i.e, 
https://github.com/m2b3/SciCommons-frontend/assets/88735632/cf03e913-1b26-430d-b056-8964fef5b758
https://github.com/m2b3/SciCommons-frontend/assets/88735632/2bc6d3aa-77df-4c0f-be0a-c2114ef0ed34

fixed dropdown and accept/reject issue in join requests page for a particular community

---

.dockerignore
Dockerfile
next.config.mjs
package.json
yarn.lock

- Added Dockerfile
- Added sharp package for image optimization on server

added Dockerfile, sharp package for image optimization on server

---

.github/workflows/deploy.yml

- deployment workflow added for frontend

deployment workflow added for frontend

---

src/app/(authentication)/auth/forgotpassword/page.tsx
src/app/(authentication)/auth/register/SignUpSuccess.tsx

issue #95 resolved, removed open gmail button.

removed open gmail button from register and forgot paswword page

---

src/app/(authentication)/auth/register/page.tsx
src/components/common/FormInput.tsx

**The following changes have been made:**
**Username Validation:**
> Added pattern to allow only lowercase letters, numbers, dots, and underscores.
> Set username length constraints (3–30 characters).
> Displayed error messages for validation issues.
**UX Enhancements:**
> Improved error handling and message display.
> Added helper text for valid username format (3–30 characters, no spaces or special symbols).
> Focused on the first error field when validation fails.
**UI Improvements:**
> Updated FormInput component for dynamic error and helper text display.
> Improved layout and styling for a better user experience.

Fix Username Validation and Improve UX for Registration Form

---

package.json
src/app/(main)/(communities)/community/[slug]/(admin)/layout.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/submissions/page.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/ArticleSubmission.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/DisplayCommunity.tsx
src/app/(main)/(communities)/community/[slug]/createcommunityarticle/page.tsx
src/components/articles/ArticleCard.tsx
src/components/articles/SearchComponent.tsx
src/components/articles/SubmitArticleForm.tsx
src/components/common/CustomTooltip.tsx
src/components/common/FormInput.tsx
src/components/common/MultiLabelSelector.tsx
src/components/common/NavBar.tsx
src/components/ui/checkbox.tsx
src/components/ui/dialog.tsx
src/components/ui/tooltip.tsx
yarn.lock

article submission changes

---

src/app/(main)/(communities)/community/[slug]/(admin)/invite/Registered.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/DisplayCommunity.tsx
src/app/(main)/(posts)/posts/[postId]/page.tsx
src/app/(main)/(users)/myprofile/PersonalLinks.tsx
src/app/(main)/(users)/myprofile/ProfessionalStatus.tsx
src/app/(main)/(users)/myprofile/Profile.tsx
src/app/(main)/(users)/myprofile/ResearchInterests.tsx
src/app/(main)/(users)/myprofile/page.tsx
src/app/(main)/(users)/notifications/page.tsx
src/components/articles/DiscussionThread.tsx
src/components/articles/DisplayArticle.tsx
src/components/articles/RelevantArticles.tsx
src/components/articles/ReviewCard.tsx
src/components/articles/ReviewComments.tsx
src/components/common/Comment.tsx
src/components/common/CommentInput.tsx
src/components/common/NavBar.tsx
src/components/common/SearchBar.tsx
src/components/common/TruncateText.tsx
src/components/communities/CommunityCard.tsx
src/components/ui/button.tsx
src/lib/convertReviewCommentData.ts

reviews and discussions in article and communities

---

src/app/(main)/(articles)/article/[slug]/(displayarticle)/page.tsx
src/components/articles/ArticleStats.tsx
src/components/articles/DiscussionCard.tsx
src/components/articles/DiscussionForm.tsx
src/components/articles/DiscussionForum.tsx
src/components/articles/ReviewCard.tsx
src/components/articles/ReviewForm.tsx

article and reviews likes removed, discussion form loading state fixed, can review self article

---

src/app/(main)/(communities)/community/[slug]/articles/[articleSlug]/page.tsx
src/components/articles/ArticleCard.tsx

discussion and comments number fixed, review form in community article

---

package.json
src/HOCs/withAuth.tsx
src/HOCs/withAuthRedirect.tsx
src/app/(main)/(communities)/community/[slug]/articles/[articleSlug]/page.tsx
src/app/(main)/layout.tsx
src/components/articles/DisplayArticle.tsx
src/components/common/Loader.tsx
src/components/common/Sidebar.tsx
src/components/ui/button.tsx
src/components/ui/sheet.tsx
src/hooks/useScaleBackground.ts
yarn.lock

sheet, drawer changes, loader changed

---

src/app/(home)/FeatureTile.tsx
src/app/(home)/FeaturesSection.tsx
src/app/(home)/page.tsx
src/app/(main)/(articles)/article/[slug]/(articledashboard)/layout.tsx
src/app/(main)/(articles)/article/[slug]/(articledashboard)/settings/page.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/StatusList.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/UnRegistered.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/layout.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/settings/EditCommunityDetails.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/submissions/page.tsx
src/app/(main)/(users)/mycontributions/ContributionCard.tsx
src/app/(main)/(users)/mycontributions/ItemCard.tsx
src/app/(main)/(users)/mycontributions/ProfileHeader.tsx
src/app/(main)/(users)/mycontributions/ReputationBadge.tsx
src/app/(main)/(users)/mycontributions/TabButton.tsx
src/app/(main)/(users)/mycontributions/page.tsx
src/components/articles/ArticleCard.tsx
src/components/articles/DisplayArticle.tsx
src/components/common/Footer.tsx
src/components/common/Sidebar.tsx
src/components/communities/TabComponent.tsx
src/components/richtexteditor/CommentEditor.tsx
src/components/richtexteditor/TipTap.tsx
src/constants/common.constants.tsx
src/hooks/useScaleBackground.ts

ui changes and fixes

---

.github/workflows/landing-page-deploy.yml

landing page deplloyment script

---

.github/workflows/alphatest-deploy.yml
.github/workflows/traefik-deploy.yml
docker-compose.alphatest.yml
docker-compose.prod.yml
docker-compose.traefik.yml

separate deployments for traefik and main, new deployment for alphatest

---

docker-compose.landing.yml

image name fix for landing page in docker compose

---

docker-compose.landing.yml

network fix docker network

---

.github/workflows/alphatest-deploy.yml
.github/workflows/deploy.yml
.github/workflows/test-deploy.yml

edit deployments

---

src/components/common/CommentInput.tsx
src/components/common/FormInput.tsx

input bg fixed

---

src/app/(main)/(users)/mycontributions/ContributionCard.tsx
src/app/(main)/(users)/mycontributions/ProfileHeader.tsx
src/app/(main)/(users)/mycontributions/ReputationBadge.tsx
src/app/(main)/(users)/mycontributions/page.tsx
src/components/articles/ReviewCard.tsx
src/components/common/BottomBar.tsx
src/components/communities/CommunityCard.tsx

contribution page ui changes, removed post from bottombar

---

src/app/(main)/(communities)/community/[slug]/(admin)/invite/Registered.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/UnRegistered.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/page.tsx
src/components/articles/ReviewForm.tsx
src/components/common/Footer.tsx

Title: There were 3 issues in the test website: -
1. Once the review is being posted, so it doesn’t clear the editor after posting the review.
2. After login, there must be no login or register button at the footer.
3. The invitation for inviting a user to join the community was not working.
Description: 1. When the user has done posting the review for an article, the editor doesn't clears the review automatically.
2. When the user doesn't login or register on the website, the footer section shows the login and register button and after the login/registering, the login and register button still appears.
3. When the admin of a community is sending the invitation to any email, the error pops up and shows "Community not found" or "Only admins can send invitation".

Solved 3 issues in the frontend.

---

src/app/(main)/(articles)/article/[slug]/(articledashboard)/settings/EditArticleDetails.tsx
src/app/(main)/(articles)/article/[slug]/(articledashboard)/settings/page.tsx
src/app/(main)/(articles)/article/[slug]/(displayarticle)/page.tsx

Title: The updates in the article were not automatically fetching.
Description: When the user updates the article, the user has to manually reload the page to view the changes. Now, the updates are being automatically fetched and shown to the user.

The updates are being automatically fetched for the article edit

---

src/app/(authentication)/auth/register/page.tsx
src/components/common/Banner.tsx

Title: Updated the releasing date of the alpha-test website and fixed the inconsitency in the username message.
Description: Updated the releasing date of the alpha-test website and fixed the inconsitency in the username message.

Updated the message on the website and fixed the username message inconsistency.

---

src/app/(authentication)/auth/login/page.tsx
src/app/(main)/(articles)/article/[slug]/(articledashboard)/community-stats/page.tsx
src/app/(main)/(articles)/article/[slug]/(articledashboard)/official-stats/page.tsx
src/app/(main)/(articles)/article/[slug]/(displayarticle)/page.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/dashboard/page.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/StatusList.tsx
src/app/(main)/(communities)/community/[slug]/(admin)/invite/page.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/ArticleSubmission.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/AssessmentsList.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/CommunityArticles.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/page.tsx
src/app/(main)/(communities)/community/[slug]/articles/[articleSlug]/page.tsx
src/app/(main)/(communities)/community/[slug]/invitations/registered/[invitation_id]/page.tsx
src/app/(main)/(communities)/community/[slug]/invitations/unregistered/[invitation_id]/[signed_email]/page.tsx
src/app/(main)/(users)/mycontributions/page.tsx
src/app/(main)/(users)/notifications/page.tsx
src/components/articles/ArticleStats.tsx
src/components/articles/DiscussionComments.tsx
src/components/articles/DiscussionForum.tsx
src/components/articles/DiscussionThread.tsx
src/components/articles/ReviewCard.tsx
src/components/articles/ReviewComments.tsx
src/components/common/Comment.tsx
src/components/common/FormInput.tsx
src/components/common/Notifications.tsx
src/components/common/PostComments.tsx
src/components/communities/CommunityCard.tsx

access token changes && login page autofocus

---

src/app/(main)/(articles)/articles/page.tsx
src/app/layout.tsx
src/components/common/NavBar.tsx
src/components/common/SearchableList.tsx
src/hooks/useKeyboardNavigation.ts

auto pagination for articles, up-down navigation

---

package.json
src/app/(main)/(articles)/articles/page.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/CommunityArticles.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/DisplayCommunity.tsx
src/app/(main)/(communities)/community/[slug]/(displaycommunity)/page.tsx
src/components/common/SearchableList.tsx
src/components/ui/resizable.tsx
src/components/ui/tab-navigation.tsx
src/hooks/useKeyboardNavigation.ts
yarn.lock

resizeable article layout for articles page and community articles page
